// Fully generated by gpt-6.1-sol
import { mkdir, writeFile } from 'node:fs/promises';

const url =
  'https://raw.githubusercontent.com/noctalia-dev/noctalia/main/src/theme/builtin_palettes.cpp';
const response = await fetch(url);
if (!response.ok)
  throw new Error(`Could not fetch palettes: ${response.status}`);
const source = await response.text();
const palettes: Record<string, Record<string, unknown>> = {};

function readBlock(text: string, field: string): string {
  const match = new RegExp(`\\.${field}\\s*=\\s*\\w+\\s*\\{`, 'u').exec(text);
  if (!match) throw new Error(`Missing ${field} block`);
  const start = match.index + match[0].length;
  let depth = 1;
  for (let i = start; i < text.length; i++) {
    if (text[i] === '{') depth++;
    if (text[i] === '}') depth--;
    if (depth === 0) return text.slice(start, i);
  }
  throw new Error(`Unclosed ${field} block`);
}

function readColors(text: string): Record<string, string> {
  const colors = Object.fromEntries(
    [...text.matchAll(/\.(\w+)\s*=\s*hex\("(#[\da-fA-F]{6})"\)/gu)].map(
      ([, token, color]) => [token, color]
    )
  );
  if (
    !Object.keys(colors).length ||
    Object.keys(colors).length !== (text.match(/hex\(/gu) ?? []).length
  ) {
    throw new Error('Could not parse colors');
  }
  return colors;
}

for (const [, name, body] of source.matchAll(
  /\.name\s*=\s*"([^"]+)"([\s\S]*?)(?=\.name\s*=\s*"|$)/gu
)) {
  palettes[name] = {};
  for (const mode of ['dark', 'light']) {
    const variant = readBlock(body, mode);
    const colors = readColors(readBlock(variant, 'palette'));
    const terminal = readBlock(variant, 'terminal');
    const normal = readBlock(terminal, 'normal');
    const bright = readBlock(terminal, 'bright');

    palettes[name][mode] = {
      ...Object.fromEntries(
        Object.entries(colors).map(([token, color]) => [
          `m${token[0].toUpperCase()}${token.slice(1)}`,
          color,
        ])
      ),
      terminal: {
        ...readColors(terminal.replace(normal, '').replace(bright, '')),
        normal: readColors(normal),
        bright: readColors(bright),
      },
    };
  }
}

if (!Object.keys(palettes).length) throw new Error('No palettes found');
const directory = new URL('../src/data/', import.meta.url);
await mkdir(directory, { recursive: true });
await writeFile(
  new URL('builtin-palettes.json', directory),
  `${JSON.stringify(palettes, null, 2)}\n`
);
console.log(`Extracted ${Object.keys(palettes).length} built-in palettes`);
